server:
  port: 8300
spring:
  application:
    name: k8s-test3
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/