apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-nginx
data:
  nginx-config: /tmp/cfg/default.conf

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test-nginx
  labels:
    app: k8s-test-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-test-nginx
  template:
    metadata:
      labels:
        app: k8s-test-nginx
    spec:
      containers:
        - image:  nginx
          name:  nginx
          volumeMounts:
            - name:  nginx-config
              mountPath:  /etc/nginx/conf.d/default.conf
              subPath: nginx-config

      volumes:
        - name:  nginx-config
          configMap:
            name: configmap-nginx

---
kind: Service
apiVersion: v1
metadata:
  name:  k8s-test-nginx-serice
spec:
  selector:
    app: k8s-test-nginx
  type:  LoadBalancer
  ports:
  - port:  80
    targetPort:  80
