apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: k8s-test-1
  labels:
    app: k8s-test-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-test-1
  template:
    metadata:
      labels:
        app: k8s-test-1
    spec:
      containers:
        - image:  tiduy1593/k8s-test-1:0.1.3
          name:  k8s-test-1
          env:
            - name: K8S_SERVICE_DISCOVERY_HOST
              value: k8s-service-discovery-service


---
kind: Service
apiVersion: v1
metadata:
  name:  k8s-test-1-service
spec:
  selector:
    app: k8s-test-1
  type:  LoadBalancer
  ports:
  - port:  80
    targetPort:  8100
