apiVersion: v1
kind: ReplicaSet
metadata:
  name: k8s-test-3
  labels:
    app: k8s-test-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-test-3
  template:
    metadata:
      labels:
        app: k8s-test-3
    spec:
      containers:
        - image:  tiduy1593/k8s-test-3
          name:  k8s-test-3
          env:
            - name:  eureka.client.serviceUrl.defaultZone
              value:  http://k8s-service-discovery-service:8761/eureka/

