apiVersion: v1
kind: ReplicaSet
metadata:
  name: k8s-test-1
  labels:
    app: k8s-test-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-test-1
  template:
    metadata:
      labels:
        app: k8s-test-1
    spec:
      containers:
        - image:  tiduy1593/k8s-test-1
          name:  k8s-test-1
          env:
            - name:  eureka.client.serviceUrl.defaultZone
              value:  http://k8s-service-discovery-service:8761/eureka/


---
kind: Service
apiVersion: v1
metadata:
  name:  k8s-test-1-service
spec:
  selector:
    app: k8s-test-1
  type:  NodePort
  ports:
  - port:  80
    targetPort:  8100