apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: k8s-test-2
  labels:
    app: k8s-test-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-test-2
  template:
    metadata:
      labels:
        app: k8s-test-2
    spec:
      containers:
        - image:  tiduy1593/k8s-test-2:0.1.1
          name:  k8s-test-2
          env:
            - name:  K8S_SERVICE_DISCOVERY_HOST
              value:  k8s-service-discovery-service

