spring:
  application:
    name: k8s-service-discovery

server:
  port: 8761
  
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 4
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
        