server:
  port: 8200
spring:
  application:
    name: k8s-test2
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/